import { RiddleStyleProps } from '../../../interfaces/screens/settings.interface';

const styleFn = (): RiddleStyleProps => ({
  root: {
    width: '100%',
    height: '100%',
    backgroundColor: '#2F2F2F',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  frame: {
    width: '90%',
    height: '95%',
    overflow: 'hidden',
    borderRadius: 8,
    padding: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subFrame: {
    width: '100%',
    height: '100%',
    backgroundColor: '#2F2F2F',
    overflow: 'hidden',
    borderRadius: 6,
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
  },
  riddleInfo: {
    position: 'absolute',
    alignSelf: 'center',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    top: 10,
  },
  riddleInfoText: {
    color: 'white',
    fontSize: 14,
    fontFamily: 'Dosis-SemiBold',
    fontWeight: '500',
  },
  questionContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    top: 4,
  },
  question: {
    color: 'white',
    fontSize: 20,
    fontFamily: 'Dosis-SemiBold',
    fontWeight: '600',
  },
  answerInput: {
    color: 'white',
    fontSize: 20,
    fontFamily: 'Dosis-SemiBold',
    backgroundColor: '#2F2F2F',
    fontWeight: '600',
    width: '100%',
    borderRadius: 6,
    paddingHorizontal: 20,
    textAlign: 'center',
  },
  button: {
    width: '100%',
    borderRadius: 8,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
    position: 'absolute',
    bottom: 40,
    padding: 3,
  },
  buttonText: {
    color: 'white',
    fontSize: 20,
    fontFamily: 'Dosis-SemiBold',
    fontWeight: '600',
    paddingHorizontal: 20,
    textAlign: 'center',
  },
  linear: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: -1,
  },
  inputContainer: {
    width: '100%',
    borderRadius: 8,
    overflow: 'hidden',
    padding: 3,
  },
  inputSubContainer: {
    zIndex: 1,
    borderRadius: 6,
  },
  onSolvedLabel: {
    color: 'white',
    fontSize: 22,
    fontFamily: 'Dosis-SemiBold',
  },
  settingsButton: {
    width: 55,
    height: 55,
    borderRadius: 8,
    overflow: 'hidden',
    padding: 3,
    margin: 2.5,
  },
  settingsButtonView: {
    bottom: 295,
    left: 148,
  },
  settings: {
    width: 30,
    height: 30,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    marginLeft: 45,
    marginRight: 50,
    backgroundColor: '#2F2F2F',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    top: 300,
    height: 300,
    width: 305,
  },
  modalButton: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  modalbuttonText: {
    color: 'white',
    fontSize: 20,
    fontFamily: 'Dosis-SemiBold',
    fontWeight: '600',
    textAlign: 'center',
    borderRadius: 7,
    width: '100%',
    height: '100%',
    textAlignVertical: 'center',
    backgroundColor: '#2F2F2F',
  },
  radioView: {
    display: 'flex',
    flexDirection: 'row',
    margin: 2,
    left: 0,
  },
  radioText: {
    color: 'white',
    fontFamily: 'Dosis-SemiBold',
    fontSize: 16,
    marginTop: 5,
  },
});

export default styleFn;
