export const riddles: any = {
  en: [
    {
      level: 'Intermediate',
      name: 'Warming Up',
      riddles: [
        {
          name: 'Following Number',
          questionptone: 'What is the next number in the following sequence',
          questionpttwo: '0 0 1 2 2 4 3 6 4 8 5 ?',
          answer: '10',
          hint: 'The number has two digits',
          isSolved: false,
          rIndex: 1,
        },
        {
          name: 'Months?',
          questionptone: 'Which month of the year has 28 days?',
          questionpttwo: '',
          answer: 'all',
          hint: 'There are more than one',
          isSolved: false,
          rIndex: 2,
        },
        {
          name: 'Whitch day?',
          questionptone: 'What day follows the day before yesterday if two days from now will be Sunday?',
          questionpttwo: '',
          answer: 'thursday',
          hint: 'three days before Sunday',
          isSolved: false,
          rIndex: 3,
        },
        {
          name: 'Word Jumble',
          questionptone: 'Make one word from all the following jumbled letters:',
          questionpttwo: 'o r e n o d w',
          answer: 'one word',
          hint: 'Just dont think complicated!',
          isSolved: false,
          rIndex: 4,
        },
        {
          name: 'Race',
          questionptone: 'You are competing in a linear race and overtake the runner in second place.',
          questionpttwo: 'In which position are you now',
          answer: 'second',
          hint: 'You take the place of the person you are overtaking',
          isSolved: false,
          rIndex: 5,
        },
        {
          name: 'Dirty',
          questionptone: 'What gets whiter the dirtier that it gets',
          questionpttwo: '',
          answer: 'board',
          hint: 'Mostly teachers use it',
          isSolved: false,
          rIndex: 6,
        },
        {
          name: 'Cold',
          questionptone: 'What grows in winter, dies in summer, and grows roots upward?',
          questionpttwo: '',
          answer: 'icicle',
          hint: 'It is cold',
          isSolved: false,
          rIndex: 7,
        },
        {
          name: 'Light',
          questionptone: 'The more of this there is, the less you see.',
          questionpttwo: 'What is it?',
          answer: 'darkness',
          hint: 'It is kind of black',
          isSolved: false,
          rIndex: 8,
        },
        {
          name: 'Nothing',
          questionptone: 'When you take more from me, I become bigger.',
          questionpttwo: 'What am I ?',
          answer: 'hole',
          hint: 'What is the entrance of Jerrys house from the Jom and Jerry series?',
          isSolved: false,
          rIndex: 9,
        },
        {
          name: 'Run',
          questionptone: 'What continues to go up and down without moving? ',
          questionpttwo: '',
          answer: 'stairs',
          hint: 'Used to switch from one floor to another',
          isSolved: false,
          rIndex: 10,
        },
        {
          name: 'Dictionary',
          questionptone: 'Which word is always spelled incorrectly in the dictionary?',
          questionpttwo: '',
          answer: 'incorrectly',
          hint: 'it is Incorrect',
          isSolved: false,
          rIndex: 11,
        },
        {
          name: 'Knowledge',
          questionptone: 'What has many words but is never able to speak?',
          questionpttwo: '',
          answer: 'Book',
          hint: 'You can read it',
          isSolved: false,
          rIndex: 12,
        },
        {
          name: 'Valuable',
          questionptone: 'I have a head but no body.',
          questionpttwo: 'What am I ?',
          answer: 'money',
          hint: 'I am valuable',
          isSolved: false,
          rIndex: 13,
        },
        {
          name: 'put-it-on',
          questionptone: 'I have a neck with no head and two arms with no hands.',
          questionpttwo: 'What am I ?',
          answer: 'pullover',
          hint: 'You can put me on.',
          isSolved: false,
          rIndex: 14,
        },
        {
          name: 'Clouds?',
          questionptone: 'What is between heaven and earth?',
          questionpttwo: '',
          answer: 'and',
          hint: 'Think simple',
          isSolved: false,
          rIndex: 15,
        },
      ],
    },
    {
      level: 'Easy',
      name: 'Starting To Adventure',
      riddles: [
        {
          name: 'Digit',
          questionptone: 'Suppose a four-digit number is an exact multiple of 9 and three of the four digits are 1, 2, and 3.',
          questionpttwo: 'What is the fourth digit?',
          answer: '3',
          hint: 'If you add the numbers, you should get 9',
          isSolved: true,
          rIndex: 16,
        },
        {
          name: 'Hungry?',
          questionptone: 'I ate one and threw away two',
          questionpttwo: '',
          answer: 'oyster',
          hint: 'It lives at sea',
          isSolved: false,
          rIndex: 17,
        },
        {
          name: 'Fly',
          questionptone: 'What flies around all day but never goes anywhere?',
          questionpttwo: '',
          answer: 'flag',
          hint: 'Not alive',
          isSolved: false,
          rIndex: 18,
        },
        {
          name: 'Security',
          questionptone: 'What is as small as a mouse but guards a house like a lion?',
          questionpttwo: '',
          answer: 'lock',
          hint: 'You can find it on every door',
          isSolved: false,
          rIndex: 19,
        },
        {
          name: 'Tik Tak',
          questionptone: 'I have two hand but I cannot clap',
          questionpttwo: 'What am I ?',
          answer: 'clock',
          hint: 'I show you the time',
          isSolved: false,
          rIndex: 20,
        },
        {
          name: 'Qwaak',
          questionptone: 'I can honk without using a horn.',
          questionpttwo: 'What am I ?',
          answer: 'goose',
          hint: 'I am an animal',
          isSolved: false,
          rIndex: 21,
        },
        {
          name: 'Power',
          questionptone: 'Whats higher than the king?',
          questionpttwo: '',
          answer: 'crown',
          hint: 'You can wear it.',
          isSolved: false,
          rIndex: 22,
        },
        {
          name: 'Electronic',
          questionptone: 'I have no life but I can die.',
          questionpttwo: 'What am I ?',
          answer: 'battery',
          hint: '',
          isSolved: false,
          rIndex: 23,
        },
        {
          name: 'Yummy!',
          questionptone: 'Sometimes I am light, sometimes I am dark.',
          questionpttwo: 'What am I ?',
          answer: 'chocolate',
          hint: 'I am yummy',
          isSolved: false,
          rIndex: 24,
        },
        {
          name: 'Vegetable',
          questionptone: 'What has many eyes but is unable to see?',
          questionpttwo: '',
          answer: 'potato',
          hint: 'It is a vegetable from germany',
          isSolved: false,
          rIndex: 25,
        },
        {
          name: 'Books',
          questionptone: 'What building has the most stories?',
          questionpttwo: '',
          answer: 'library',
          hint: 'Its full of books there',
          isSolved: false,
          rIndex: 26,
        },
        {
          name: 'Burn',
          questionptone: 'I am always hungry and will die if not fed but whatever I touch will turn to red. ',
          questionpttwo: 'What am I ?',
          answer: 'fire',
          hint: 'They call the fire department for me',
          isSolved: false,
          rIndex: 27,
        },
        {
          name: 'Dark',
          questionptone: 'What can be seen but not touched?',
          questionpttwo: '',
          answer: 'shadow',
          hint: 'It is always with you.',
          isSolved: false,
          rIndex: 28,
        },
        {
          name: 'Style',
          questionptone: 'It has its teeth on your head but doesnt bite.',
          questionpttwo: '',
          answer: 'comb',
          hint: 'You comb your hair with it.',
          isSolved: false,
          rIndex: 29,
        },
        {
          name: 'Blind?',
          questionptone: 'The more you look at it, The less you see.',
          questionpttwo: '',
          answer: 'sun',
          hint: 'Light source of the world',
          isSolved: false,
          rIndex: 30,
        },
      ],
    },
    {
      level: 'Medium',
      name: 'Running Into Temple',
      riddles: [
        {
          name: 'Doctor',
          questionptone: 'A doctor’s son’s father was not a doctor.',
          questionpttwo: 'Who is the doctor?',
          answer: 'the mother',
          hint: 'If this is the son and the doctor is not the father, it can only be one of the parents',
          isSolved: false,
          rIndex: 31,
        },
        {
          name: 'Iron',
          questionptone: 'Iron roof, glass walls ,burns and burns and never falls.',
          questionpttwo: '',
          answer: 'latern',
          hint: 'The answer is a source of light',
          isSolved: false,
          rIndex: 32,
        },
        {
          name: 'Gambling',
          questionptone: 'What can you fold but not crease?',
          questionpttwo: '',
          answer: 'poker hand',
          hint: 'Think of gambling',
          isSolved: false,
          rIndex: 33,
        },
        {
          name: '?',
          questionptone: 'What is given but kept by the giver',
          questionpttwo: '',
          answer: 'birth',
          hint: 'It is a thing only women can do',
          isSolved: false,
          rIndex: 34,
        },
        {
          name: 'Water',
          questionptone: 'With head without hair. With mouth without tooth.',
          questionpttwo: 'What am I?',
          answer: 'bottle',
          hint: 'Water fills in',
          isSolved: false,
          rIndex: 35,
        },
        {
          name: 'Eeeewww',
          questionptone: 'This small creature kills even the largest one.',
          questionpttwo: '',
          answer: 'bacteria',
          hint: 'I make you ill.',
          isSolved: false,
          rIndex: 36,
        },
        {
          name: 'Creativity',
          questionptone: 'As your Ideas grows , I shrink.',
          questionpttwo: 'What am I ?',
          answer: 'pencil',
          hint: 'You can write with me.',
          isSolved: false,
          rIndex: 37,
        },
        {
          name: 'Trust',
          questionptone: 'What can you keep after giving it to someone',
          questionpttwo: '',
          answer: 'secret',
          hint: 'It is important for you',
          isSolved: false,
          rIndex: 38,
        },
        {
          name: 'Noises',
          questionptone: 'I speak without a mouth and hear without ears.',
          questionpttwo: 'What am I ?',
          answer: 'echo',
          hint: 'Something that happens when you shout in a Tunnel.',
          isSolved: false,
          rIndex: 39,
        },
        {
          name: 'Fish',
          questionptone: 'First you eat me, and then you get eaten.',
          questionpttwo: 'What am I ?',
          answer: 'fishhook',
          hint: 'You use me to attract fishes',
          isSolved: false,
          rIndex: 40,
        },
        {
          name: 'Comfortable',
          questionptone: 'Sitting down you have it, Standing up you dont',
          questionpttwo: '',
          answer: 'lap',
          hint: 'Babys or kids sit mostly on it.',
          isSolved: false,
          rIndex: 41,
        },
        {
          name: 'Fruit',
          questionptone: 'What fruit is of great use in history',
          questionpttwo: '',
          answer: 'date',
          hint: 'Arabia is famous for it',
          isSolved: false,
          rIndex: 42,
        },
        {
          name: 'USA',
          questionptone: 'What is round on both ends and hi in the middle',
          questionpttwo: '',
          answer: 'ohio',
          hint: 'It is an US-State',
          isSolved: false,
          rIndex: 43,
        },
        {
          name: 'Fast',
          questionptone: 'I pass before the sun, yet make no shadow.',
          questionpttwo: 'What am I ?',
          answer: 'wind',
          hint: 'Sometimes I am cold but sometimes refreshing',
          isSolved: false,
          rIndex: 44,
        },
        {
          name: 'Fly',
          questionptone: 'Who spends the day at the window, goes to the table for meals, and hides at night?',
          questionpttwo: '',
          answer: 'fly',
          hint: 'Its annoying',
          isSolved: false,
          rIndex: 45,
        },
      ],
    },
    {
      level: 'Hard',
      name: 'Last Step',
      riddles: [
        {
          name: 'Following Letter',
          questionptone: 'What is the next letter in the following series :',
          questionpttwo: 'y z v w s t p q?',
          answer: 'm',
          hint: 'Pay attention to the pairs of letters look for the scheme',
          isSolved: false,
          rIndex: 46,
        },
        {
          name: 'Wood',
          questionptone: 'What is made of wood but cant be sawed',
          questionpttwo: '',
          answer: 'sawdust',
          hint: 'Very small Wood.',
          isSolved: false,
          rIndex: 47,
        },
        {
          name: 'Math',
          questionptone: 'If eleven plus two equals one, what does nine plus five equal? ',
          questionpttwo: '',
          answer: '2',
          hint: 'Think about the clock.',
          isSolved: false,
          rIndex: 48,
        },
        {
          name: 'Small',
          questionptone: 'What animal has feet on the head?',
          questionpttwo: '',
          answer: 'lice',
          hint: 'It is small',
          isSolved: false,
          rIndex: 49,
        },
        {
          name: 'Burn',
          questionptone: 'I am not alive, but I grow; I dont have lungs, but I need air; I dont have a mouth, but water kills me.',
          questionpttwo: 'What am I?',
          answer: 'fire',
          hint: 'I am mostly red and yellow',
          isSolved: false,
          rIndex: 50,
        },
        {
          name: 'High',
          questionptone: 'I am not alive, but I can die; I dont have wings, but I can fly; I dont have eyes, but I can cry.',
          questionpttwo: 'What am I?',
          answer: 'cloud',
          hint: 'I am in the sky',
          isSolved: false,
          rIndex: 51,
        },
        {
          name: 'Life',
          questionptone: 'I am light as a feather, yet the strongest person cannot hold me for much more than a minute.',
          questionpttwo: 'What am I?',
          answer: 'breath',
          hint: 'Everyone needs it',
          isSolved: false,
          rIndex: 52,
        },
        {
          name: 'Smart',
          questionptone: 'I am taken from a mine, and shut up in a wooden case, from which I am never released, and yet I am used by almost every person.',
          questionpttwo: 'What am I?',
          answer: 'lead',
          hint: 'You can produce a pencil with me',
          isSolved: false,
          rIndex: 53,
        },
        {
          name: 'Blind',
          questionptone: 'Without a bridle or a saddle, across a thing I ride a-straddle. And those I ride, by help of me, though almost blind, are made to see.',
          questionpttwo: 'What am I?',
          answer: 'Eyeglasses',
          hint: 'Thats what people with poor eyesight need',
          isSolved: false,
          rIndex: 54,
        },
        {
          name: 'Trust2',
          questionptone: 'If you have me, you want to share me. If you share me, you dont have me.',
          questionpttwo: 'What am I?',
          answer: 'secret',
          hint: 'Are you trustworthy?',
          isSolved: false,
          rIndex: 55,
        },
        {
          name: 'Counter',
          questionptone: 'What are the next three letters in this combination?',
          questionpttwo: 'O T T F F S S',
          answer: 'ent',
          hint: 'Start to count',
          isSolved: false,
          rIndex: 56,
        },
        {
          name: 'World',
          questionptone: 'I have cities, but not houses. I have mountains, but no trees. I have coasts, but no sand.',
          questionpttwo: 'What am I?',
          answer: 'map',
          hint: 'You can find the way with me',
          isSolved: false,
          rIndex: 57,
        },
        {
          name: 'Post',
          questionptone: 'What can travel all around the world while remaining stuck in a corner?',
          questionpttwo: '',
          answer: 'stamp',
          hint: 'You can paste me on a letter',
          isSolved: false,
          rIndex: 58,
        },
        {
          name: 'Snow',
          questionptone: 'What has four fingers and a thumb but isnt alive?',
          questionpttwo: '',
          answer: 'glove',
          hint: 'Most people wear me for snow',
          isSolved: false,
          rIndex: 59,
        },
        {
          name: 'QUIET',
          questionptone: 'What disappears the moment you say its name?',
          questionpttwo: '',
          answer: 'silence',
          hint: 'Be quiet',
          isSolved: false,
          rIndex: 60,
        },
      ],
    },
  ],
  de: [
    {
      level: 'Anfänger',
      name: 'Aufwärmen',
      riddles: [
        {
          name: 'Nächste Ziffer',
          questionptone: 'Was ist die nächste Zahl in der folgenden Reihe',
          questionpttwo: '0 0 1 2 2 4 3 6 4 8 5 ?',
          answer: '10',
          hint: 'Die Zahl ist zwei stellig',
          isSolved: false,
          rIndex: 1,
        },
        { name: 'Monate', questionptone: 'Welcher Monat hat 28 Tage?', questionpttwo: '', answer: 'alle', hint: 'Es gibt mehr als eine', isSolved: false, rIndex: 2 },
        {
          name: 'Welcher tag?',
          questionptone: 'Welcher Tag folgt auf Vorgestern, wenn in zwei Tagen Sonntag sein wird?',
          questionpttwo: '',
          answer: 'donnerstag',
          hint: 'Drei Tage vor Sonntag',
          isSolved: false,
          rIndex: 3,
        },
        {
          name: 'Wörter Salat',
          questionptone: 'Bilde ein Wort aus allen folgenden durcheinandergewürfelten Buchstaben:',
          questionpttwo: 'o r w t e n i',
          answer: 'ein wort',
          hint: 'Denke nicht kompliziert!',
          isSolved: false,
          rIndex: 4,
        },
        {
          name: 'Rennen',
          questionptone: 'Du überholst in einem Wettrennen den zweiten Platz',
          questionpttwo: 'Welcher Platz bist du nun?',
          answer: 'zweiter',
          hint: 'Du nimmst den Platz ein den du überholst',
          isSolved: false,
          rIndex: 5,
        },
        {
          name: 'Dreckig',
          questionptone: 'Je weißer es wird, desto schmutziger wird es',
          questionpttwo: '',
          answer: 'tafel',
          hint: 'Meistens benutzen es Lehrer',
          isSolved: false,
          rIndex: 6,
        },
        {
          name: 'Kalt',
          questionptone: 'Was wächst im Winter, stirbt im Sommer und treibt Wurzeln nach oben?',
          questionpttwo: '',
          answer: 'eiszapfen',
          hint: 'Es ist kalt',
          isSolved: false,
          rIndex: 7,
        },
        {
          name: 'Licht',
          questionptone: 'Je mehr davon vorhanden ist, desto weniger sieht man.',
          questionpttwo: 'Was ist das?',
          answer: 'dunkel',
          hint: 'Das ist irgendwie schwarz',
          isSolved: false,
          rIndex: 8,
        },
        {
          name: 'Nichts',
          questionptone: 'Je mehr du von mir nimmst desto größer werde ich.',
          questionpttwo: 'Was bin ich ?',
          answer: 'loch',
          hint: 'Was ist der Eingang von Jerrys Haus aus der Serie Tom und Jerry',
          isSolved: false,
          rIndex: 9,
        },
        {
          name: 'Renn',
          questionptone: 'Was geht weiterhin auf und ab, ohne sich zu bewegen?',
          questionpttwo: '',
          answer: 'treppen',
          hint: 'Wird verwendet, um von einer Etage zur anderen zu wechseln',
          isSolved: false,
          rIndex: 10,
        },
        {
          name: 'Worterbuch',
          questionptone: 'Welches Wort wird im Wörterbuch immer falsch geschrieben?',
          questionpttwo: '',
          answer: 'falsch',
          hint: 'Es ist falsch',
          isSolved: false,
          rIndex: 11,
        },
        {
          name: 'Wissen',
          questionptone: 'Was hat viele Worte, kann aber nie sprechen?',
          questionpttwo: '',
          answer: 'buch',
          hint: 'Man kann es lesen',
          isSolved: false,
          rIndex: 12,
        },
        {
          name: 'Wertvoll',
          questionptone: 'Ich habe einen Kopf, aber keinen Körper.',
          questionpttwo: 'Was bin ich ?',
          answer: 'geld',
          hint: 'Ich bin wertvoll',
          isSolved: false,
          rIndex: 13,
        },
        {
          name: 'Zieh-es-an',
          questionptone: 'Ich habe einen Hals ohne Kopf und zwei Arme ohne Hände.',
          questionpttwo: 'Was bin ich ?',
          answer: 'pullover',
          hint: 'Du kannst mich anziehen.',
          isSolved: false,
          rIndex: 14,
        },
        {
          name: 'Wolken?',
          questionptone: 'Was ist zwischen Himmel und Erde?',
          questionpttwo: '',
          answer: 'und',
          hint: 'Denke einfach',
          isSolved: false,
          rIndex: 15,
        },
      ],
    },
    {
      level: 'Leicht',
      name: 'Das Abenteuer beginnt',
      riddles: [
        {
          name: 'Ziffer',
          questionptone: 'Angenommen, eine vierstellige Zahl ist ein exaktes Vielfaches von 9 und drei der vier Ziffern sind 1, 2 und 3.',
          questionpttwo: 'Was ist die vierte Ziffer?',
          answer: '3',
          hint: 'Wenn du die Zahlen addierst sollte 9 rauskommen',
          isSolved: true,
          rIndex: 16,
        },
        {
          name: 'Hungrig?',
          questionptone: 'Ich esse eins und werfe zwei weg',
          questionpttwo: '',
          answer: 'muschel',
          hint: 'Es lebt im see',
          isSolved: false,
          rIndex: 17,
        },
        {
          name: 'Fiegen',
          questionptone: 'Was fliegt den ganzen Tag herum, geht aber nirgendwo hin?',
          questionpttwo: '',
          answer: 'flagge',
          hint: 'Es lebt nicht',
          isSolved: false,
          rIndex: 18,
        },
        {
          name: 'Sicherheit',
          questionptone: 'Was ist so klein wie eine Maus, bewacht aber ein Haus wie ein Löwe?',
          questionpttwo: '',
          answer: 'schloss',
          hint: 'Du kannst es an jeder Tür finden',
          isSolved: false,
          rIndex: 19,
        },
        {
          name: 'Tik Tak',
          questionptone: 'Ich hab zwei Hände aber kann nicht klatschen',
          questionpttwo: 'Was bin ich ?',
          answer: 'uhr',
          hint: 'Ich zeige dir die Uhrzeit.',
          isSolved: false,
          rIndex: 20,
        },
        {
          name: 'Qwaak',
          questionptone: 'Ich kann ohne eine Horn tuten.',
          questionpttwo: 'Was bin ich ?',
          answer: 'gans',
          hint: 'Ich bin ein Tier.',
          isSolved: false,
          rIndex: 21,
        },
        {
          name: 'Macht',
          questionptone: 'Was ist höher als der König?',
          questionpttwo: '',
          answer: 'krone',
          hint: 'Man kann es anziehen',
          isSolved: false,
          rIndex: 22,
        },
        {
          name: 'Elektronisch',
          questionptone: 'Ich habe kein Leben, aber ich kann sterben.',
          questionpttwo: 'Was bin ich ?',
          answer: 'batterie',
          hint: '',
          isSolved: false,
          rIndex: 23,
        },
        {
          name: 'Lecker!',
          questionptone: 'Manchmal bin ich hell, manchmal bin ich dunkel.',
          questionpttwo: 'Was bin ich ?',
          answer: 'schokolade',
          hint: 'Ich bin lecker',
          isSolved: false,
          rIndex: 24,
        },
        {
          name: 'Gemüse',
          questionptone: 'Was hat viele Augen, kann aber nicht sehen?',
          questionpttwo: '',
          answer: 'potato',
          hint: 'Es ist gemüse von Deutschland',
          isSolved: false,
          rIndex: 25,
        },
        {
          name: 'Bücher',
          questionptone: 'Welches Gebäude hat die meisten Geschichten?',
          questionpttwo: '',
          answer: 'Bücherei',
          hint: 'Dort ist es voll it Büchern',
          isSolved: false,
          rIndex: 26,
        },
        {
          name: 'Brenn',
          questionptone: 'Ich habe immer Hunger und sterbe, wenn ich nichts zu essen bekomme, aber alles, was ich anfasse, wird rot.',
          questionpttwo: 'Was bin ich ?',
          answer: 'feuer',
          hint: 'Man ruft die Feuerwehr für mich',
          isSolved: false,
          rIndex: 27,
        },
        {
          name: 'Dunkel',
          questionptone: 'Was kann man sehen, aber nicht anfassen?',
          questionpttwo: '',
          answer: 'schatten',
          hint: 'Es ist immer mit dir.',
          isSolved: false,
          rIndex: 28,
        },
        {
          name: 'Style',
          questionptone: 'Es hat seine Zähne auf deinem Kopf, beißt aber nicht.',
          questionpttwo: '',
          answer: 'kamm',
          hint: 'Du kämmst damit deine Haare.',
          isSolved: false,
          rIndex: 29,
        },
        {
          name: 'Blind?',
          questionptone: 'Je mehr man es betrachtet, desto weniger sieht man.',
          questionpttwo: '',
          answer: 'sonne',
          hint: 'Lichtquelle der Welt',
          isSolved: false,
          rIndex: 30,
        },
      ],
    },
    {
      level: 'Mittel',
      name: 'Hinter Rätsel',
      riddles: [
        {
          name: 'Doktor',
          questionptone: 'Der Vater eines Arztesohns war kein Arzt.',
          questionpttwo: 'Wer ist dann Arzt',
          answer: 'die mutter',
          hint: 'Handelt es sich dabei um den Sohn und der Arzt nicht um den Vater, kann es sich nur um einen Elternteil handeln',
          isSolved: false,
          rIndex: 31,
        },
        {
          name: 'Eisen',
          questionptone: 'Eisendach, Glaswände, brennt und brennt und fällt nie.',
          questionpttwo: '',
          answer: 'laterne',
          hint: 'Die Antwort ist eine Lichtquelle',
          isSolved: false,
          rIndex: 32,
        },
        {
          name: 'Glücksspiel',
          questionptone: 'Was kann man falten, aber nicht knittern?',
          questionpttwo: '',
          answer: 'poker hand',
          hint: 'Denke an glückspiele',
          isSolved: false,
          rIndex: 33,
        },
        {
          name: '?',
          questionptone: 'Was gegeben, aber vom Geber behalten wird',
          questionpttwo: '',
          answer: 'geburt',
          hint: 'Es ist eine Sache die nur Frauen machen können',
          isSolved: false,
          rIndex: 34,
        },
        {
          name: 'Wasser',
          questionptone: 'Mit Kopf ohne Haare. Mit Mund ohne Zähne.',
          questionpttwo: 'Was bin ich?',
          answer: 'flasche',
          hint: 'Man kann Wasser einfüllen',
          isSolved: false,
          rIndex: 35,
        },
        {
          name: 'Eeeewww',
          questionptone: 'Diese kleine Kreatur tötet selbst die Größten.',
          questionpttwo: '',
          answer: 'bakterie',
          hint: 'Ich mache dich krank',
          isSolved: false,
          rIndex: 36,
        },
        {
          name: 'Kreativität',
          questionptone: 'Während deine Ideen wachsen, schrumpfe ich.',
          questionpttwo: 'Was bin ich ?',
          answer: 'stift',
          hint: 'Du kannst mit mir schreiben.',
          isSolved: false,
          rIndex: 37,
        },
        {
          name: 'Vertrauen',
          questionptone: 'Was können Sie behalten, nachdem Sie es jemandem gegeben haben?',
          questionpttwo: '',
          answer: 'geheimnis',
          hint: 'Es ist wichtig für dich',
          isSolved: false,
          rIndex: 38,
        },
        {
          name: 'Stimmen',
          questionptone: 'Ich spreche ohne Mund und höre ohne Ohren.',
          questionpttwo: 'Was bin ich ?',
          answer: 'echo',
          hint: 'Etwas, das passiert, wenn man in einem Tunnel schreit.',
          isSolved: false,
          rIndex: 39,
        },
        {
          name: 'Fisch',
          questionptone: 'Zuerst isst du mich und dann wirst du gegessen.',
          questionpttwo: 'Was bin ich ?',
          answer: 'angelhaken',
          hint: 'Du benutzt mich, um Fische anzulocken',
          isSolved: false,
          rIndex: 40,
        },
        {
          name: 'Bequem',
          questionptone: 'Im Sitzen hat man es, im Stehen nicht',
          questionpttwo: '',
          answer: 'schoß',
          hint: 'Meist sitzen Babys oder Kinder darauf.',
          isSolved: false,
          rIndex: 41,
        },
        {
          name: 'Frucht',
          questionptone: 'Welche Frucht ist in der Geschichte von großem Nutzen?',
          questionpttwo: '',
          answer: 'datteln',
          hint: 'Arabien ist dafür bekannt',
          isSolved: false,
          rIndex: 42,
        },
        {
          name: 'USA',
          questionptone: 'Was an beiden Enden rund und hi in der Mitte',
          questionpttwo: '',
          answer: 'ohio',
          hint: 'Es ist eine US-Staat',
          isSolved: false,
          rIndex: 43,
        },
        {
          name: 'Schnell',
          questionptone: 'Ich gehe vor der Sonne vorbei und mache doch keinen Schatten.',
          questionpttwo: 'Was bin ich ?',
          answer: 'wind',
          hint: 'Manchmal bin ich kalt doch manchmal erfrischend',
          isSolved: false,
          rIndex: 44,
        },
        {
          name: 'Fliegen',
          questionptone: 'Wer verbringt den Tag am Fenster, geht zum Essen an den Tisch und versteckt sich nachts?',
          questionpttwo: '',
          answer: 'fliege',
          hint: 'Es ist nervig',
          isSolved: false,
          rIndex: 45,
        },
      ],
    },
    {
      level: 'Schwer',
      name: 'Letzter Schritt',
      riddles: [
        {
          name: 'Nächster Buchstabe',
          questionptone: 'Was ist der nächste Buchstabe in der folgenden Reihe:',
          questionpttwo: 'y z v w s t p q?',
          answer: 'm',
          hint: 'Achten Sie auf die Buchstabenpaare und suchen Sie nach dem Schema',
          isSolved: false,
          rIndex: 46,
        },
        {
          name: 'Holz',
          questionptone: 'Was aus Holz ist, aber nicht gesägt werden kann',
          questionpttwo: '',
          answer: 'streu',
          hint: 'Sehr kleines Holz',
          isSolved: false,
          rIndex: 47,
        },
        {
          name: 'Mathe',
          questionptone: 'Wenn elf plus zwei gleich eins ist, was ergibt dann neun plus fünf?',
          questionpttwo: '',
          answer: '2',
          hint: 'Denk an die Uhr.',
          isSolved: false,
          rIndex: 48,
        },
        {
          name: 'Klein',
          questionptone: 'Welches Tier hat Füße auf dem Kopf?',
          questionpttwo: '',
          answer: 'Läuse',
          hint: 'Es ist klein',
          isSolved: false,
          rIndex: 49,
        },
        {
          name: 'Brennen',
          questionptone: 'Ich lebe nicht, aber ich wachse; Ich habe keine Lunge, aber ich brauche Luft; Ich habe keinen Mund, aber Wasser bringt mich um.',
          questionpttwo: 'Was bin ich?',
          answer: 'feuer',
          hint: 'Ich bin hauptsächlich rot und gelb',
          isSolved: false,
          rIndex: 50,
        },
        {
          name: 'Hoch',
          questionptone: 'Ich bin nicht am Leben, aber ich kann sterben; Ich habe keine Flügel, aber ich kann fliegen; Ich habe keine Augen, aber ich kann weinen.',
          questionpttwo: 'Was bin ich?',
          answer: 'wolke',
          hint: 'Ich bin im Himmel',
          isSolved: false,
          rIndex: 51,
        },
        {
          name: 'Leben',
          questionptone: 'Ich bin leicht wie eine Feder, doch der stärkste Mensch kann mich nicht viel länger als eine Minute halten.',
          questionpttwo: 'Was bin ich?',
          answer: 'atem',
          hint: 'Jeder braucht es',
          isSolved: false,
          rIndex: 52,
        },
        {
          name: 'Smart',
          questionptone: 'Ich werde aus einer Mine geholt und in eine Holzkiste gesperrt, aus der ich niemals entlassen werde, und doch werde ich von fast jedem Menschen benutzt.',
          questionpttwo: 'Was bin ich?',
          answer: 'blei',
          hint: 'Du kannst mit mir einen Bleistift herstellen',
          isSolved: false,
          rIndex: 53,
        },
        {
          name: 'Blind',
          questionptone:
            'Ohne Zaumzeug oder Sattel reite ich im Grätsch über ein Ding.“ Und diejenigen, die ich reite, werden mit meiner Hilfe sehend gemacht, obwohl sie fast blind sind.',
          questionpttwo: 'Was bin ich?',
          answer: 'brille',
          hint: 'Das brauchen Menschen mit Sehschwäche',
          isSolved: false,
          rIndex: 54,
        },
        {
          name: 'Trust2',
          questionptone: 'Wenn du mich hast, willst du mich teilen. Wenn du mich teilst, hast du mich nicht.',
          questionpttwo: 'Was bin ich?',
          answer: 'geheimnis',
          hint: 'Bist du vertrauenswürdig?',
          isSolved: false,
          rIndex: 55,
        },
        {
          name: 'Zahlen',
          questionptone: 'Was sind die nächsten drei Buchstaben in dieser Kombination?',
          questionpttwo: 'E Z D V F S S',
          answer: 'anz',
          hint: 'Beginne mit dem Zählen',
          isSolved: false,
          rIndex: 56,
        },
        {
          name: 'Welt',
          questionptone: 'Ich habe Städte, aber keine Häuser. Ich habe Berge, aber keine Bäume. Ich habe Küsten, aber keinen Sand.',
          questionpttwo: 'Was bin ich?',
          answer: 'karte',
          hint: 'Du kannst den Weg mit mir finden',
          isSolved: false,
          rIndex: 57,
        },
        {
          name: 'Post',
          questionptone: 'Was kann um die Welt reisen und dabei in der Ecke stecken bleiben?',
          questionpttwo: '',
          answer: 'briefmarke',
          hint: 'Du kannst mich an einen Brief kleben',
          isSolved: false,
          rIndex: 58,
        },
        {
          name: 'Schnee',
          questionptone: 'Was hat vier Finger und einen Daumen, ist aber nicht lebendig?',
          questionpttwo: '',
          answer: 'Handschuh',
          hint: 'Die meisten Leute tragen mich bei Schnee',
          isSolved: false,
          rIndex: 59,
        },
        {
          name: 'RUHIG',
          questionptone: 'Was verschwindet, sobald du seinen Namen sagst?',
          questionpttwo: '',
          answer: 'stille',
          hint: 'Sei still',
          isSolved: false,
          rIndex: 60,
        },
      ],
    },
  ],
  tr: [
    {
      level: 'Acemi',
      name: 'Isinma',
      riddles: [
        {
          name: 'Sonraki rakam',
          questionptone: 'Aşağıdaki dizide bir sonraki sayı nedir?',
          questionpttwo: '0 0 1 2 2 4 3 6 4 8 5 ?',
          answer: '10',
          hint: 'Sayi iki haneli',
          isSolved: false,
          rIndex: 1,
        },
        { name: 'Aylar', questionptone: 'Yılın hangi ayında 28 gün vardır?', questionpttwo: '', answer: 'hepsinde', hint: 'Birden fazla var', isSolved: false, rIndex: 2 },
        {
          name: 'Hangi gün?',
          questionptone: 'İki gün sonra Pazar olacaksa, dünden önceki günü hangi gün takip eder?',
          questionpttwo: '',
          answer: 'perşembe',
          hint: 'Pazar gününden üç gün önce',
          isSolved: false,
          rIndex: 3,
        },
        {
          name: 'Kelime Karmaşası',
          questionptone: 'Aşağıdaki karışık harflerden bir kelime oluşturun:',
          questionpttwo: 'k b e i r l m i e',
          answer: 'bir kelime',
          hint: 'Karmaşık düşünmeyin!',
          isSolved: false,
          rIndex: 4,
        },
        {
          name: 'Yarıs',
          questionptone: 'Bir yarışta yarışıyorsunuz ve ikinci sıradaki koşucuyu geçiyorsunuz.',
          questionpttwo: 'Şimdi hangi sıradasın?',
          answer: 'ikinci',
          hint: 'Geçtiğin yeri alırsın',
          isSolved: false,
          rIndex: 5,
        },
        {
          name: 'Kirli',
          questionptone: 'Kirlendikçe beyazlaşan şey nedir?',
          questionpttwo: '',
          answer: 'tahta',
          hint: 'Genelde öğretmenler kullanır',
          isSolved: false,
          rIndex: 6,
        },
        {
          name: 'Soğuk',
          questionptone: 'Kışın büyüyen, yazın ölen ve yukarı doğru kök salan nedir?',
          questionpttwo: '',
          answer: 'buz',
          hint: 'Bu kelime soğuk birşey',
          isSolved: false,
          rIndex: 7,
        },
        {
          name: 'Işık',
          questionptone: 'Bundan ne kadar çok varsa, o kadar az görürsün.',
          questionpttwo: 'Bu nedir?',
          answer: 'karanlık',
          hint: 'Bir bakımdan biraz siyah',
          isSolved: false,
          rIndex: 8,
        },
        {
          name: 'Boşluk',
          questionptone: 'Benden nekadar alırsan okadar büyürüm.',
          questionpttwo: 'Ben neyim ?',
          answer: 'delik',
          hint: 'Tom ve Jerry serisinden Jerry nin evinin girişi nedir?',
          isSolved: false,
          rIndex: 9,
        },
        {
          name: 'Koş',
          questionptone: 'Hareket etmeden yukarı ve aşağı gitmeye devam eden nedir?',
          questionpttwo: '',
          answer: 'merdiven',
          hint: 'Bir kattan başka bir kata geçiş yapmak için kullanılır',
          isSolved: false,
          rIndex: 10,
        },
        {
          name: 'Sözlük',
          questionptone: 'Sözlükte hangi kelime her zaman yanlış yazılır?',
          questionpttwo: '',
          answer: 'yanlış',
          hint: 'Bu yanlış',
          isSolved: false,
          rIndex: 11,
        },
        {
          name: 'Bilgi',
          questionptone: 'Çok sözü olan ama asla konuşamayan şey nedir?',
          questionpttwo: '',
          answer: 'kitap',
          hint: 'Onu okuyabilirsin',
          isSolved: false,
          rIndex: 12,
        },
        {
          name: 'Değerli',
          questionptone: 'Başım var ama bedenim yok.',
          questionpttwo: 'Ben neyim ?',
          answer: 'para',
          hint: 'Ben değerliyim',
          isSolved: false,
          rIndex: 13,
        },
        {
          name: 'üstüne-giyin',
          questionptone: 'Başsız bir boynum ve elim olmayan iki kolum var.',
          questionpttwo: 'Ben neyim ?',
          answer: 'kazak',
          hint: 'Beni giyebilirsin.',
          isSolved: false,
          rIndex: 14,
        },
        {
          name: 'Bulutlar?',
          questionptone: 'Cennet ve dünya arasında ne var?',
          questionpttwo: '',
          answer: 've',
          hint: 'Kolay düşün',
          isSolved: false,
          rIndex: 15,
        },
      ],
    },
    {
      level: 'Kolay',
      name: 'Macera basliyor',
      riddles: [
        {
          name: 'Rakamlar',
          questionptone: 'Dört basamaklı bir sayının 9`un tam katı olduğunu ve dört basamaktan üçünün 1, 2 ve 3 olduğunu varsayalım.',
          questionpttwo: 'Dördüncü rakam nedir?',
          answer: '3',
          hint: 'Sayıları toplarsan 9 elde edersin.',
          isSolved: true,
          rIndex: 16,
        },
        {
          name: 'Aciktinmi?',
          questionptone: 'Birini yedim ikisini çöpe attım',
          questionpttwo: '',
          answer: 'Midye',
          hint: 'Denizde yaşar',
          isSolved: false,
          rIndex: 17,
        },
        {
          name: 'Uçmak',
          questionptone: 'Bütün gün havada uçuşan ama hiçbir yere gitmeyen şey nedir?',
          questionpttwo: '',
          answer: 'bayrak',
          hint: 'Canlı değil',
          isSolved: false,
          rIndex: 18,
        },
        {
          name: 'Güvenlik',
          questionptone: 'Fare kadar küçük olan ama evi aslan gibi koruyan nedir?',
          questionpttwo: '',
          answer: 'kilit',
          hint: 'Her kapıda bulabilirsin',
          isSolved: false,
          rIndex: 19,
        },
        {
          name: 'Tik Tak',
          questionptone: 'Iki elim var ama alkışlayamam',
          questionpttwo: 'Ben neyim ?',
          answer: 'saat',
          hint: 'Sana vakiti gösteririm',
          isSolved: false,
          rIndex: 20,
        },
        {
          name: 'Qwaak',
          questionptone: 'Boru kullanmadan ötebiliyorum.',
          questionpttwo: 'Ben neyim ?',
          answer: 'kaz',
          hint: 'Ben bir hayvanım.',
          isSolved: false,
          rIndex: 21,
        },
        {
          name: 'Güç',
          questionptone: 'Kraldan daha yüksek olan nedir?',
          questionpttwo: '',
          answer: 'taç',
          hint: 'Onu giyebilirsin',
          isSolved: false,
          rIndex: 22,
        },
        {
          name: 'Elektronik',
          questionptone: 'Hayatım yok ama ölebilirim.',
          questionpttwo: 'Ben neyim ?',
          answer: 'batarya',
          hint: 'Ben elektronik bir şeyim',
          isSolved: false,
          rIndex: 23,
        },
        {
          name: 'Lezzetli!',
          questionptone: 'Bazen açığım, bazen karanlık.',
          questionpttwo: 'Ben neyim ?',
          answer: 'çikolata',
          hint: 'Ben lezzetliyim',
          isSolved: false,
          rIndex: 24,
        },
        {
          name: 'Sebze',
          questionptone: 'Çok gözü olan ama göremeyen nedir?',
          questionpttwo: '',
          answer: 'patates',
          hint: 'Almanyadan gelen bir sebze',
          isSolved: false,
          rIndex: 25,
        },
        {
          name: 'Kitaplar',
          questionptone: 'En çok hikayesi olan bina hangisidir',
          questionpttwo: '',
          answer: 'kütüphane',
          hint: 'Orası kitap lar ile dolu',
          isSolved: false,
          rIndex: 26,
        },
        {
          name: 'Yan',
          questionptone: 'Her zaman açım ve beslenmezsem öleceğim ama dokunduğum her şey kırmızıya dönecek.',
          questionpttwo: 'Ben neyim ?',
          answer: 'ateş',
          hint: 'Benim için itfaiyeyi ararlar.',
          isSolved: false,
          rIndex: 27,
        },
        {
          name: 'Karanlık',
          questionptone: 'Görülebilen ama dokunulamayan ne var?',
          questionpttwo: '',
          answer: 'gölge',
          hint: 'O hep seninledir',
          isSolved: false,
          rIndex: 28,
        },
        {
          name: 'Style',
          questionptone: 'Başında dişleri var ama ısırmıyor.',
          questionpttwo: '',
          answer: 'tarak',
          hint: 'Onunla saçını tararsın',
          isSolved: false,
          rIndex: 29,
        },
        {
          name: 'Kör?',
          questionptone: 'Ne kadar çok bakarsan, o kadar az görürsün.',
          questionpttwo: '',
          answer: 'güneş',
          hint: 'Dünyanın ışık kaynağı',
          isSolved: false,
          rIndex: 30,
        },
      ],
    },
    {
      level: 'Orta',
      name: 'Gizem pesinde',
      riddles: [
        {
          name: 'Doktor',
          questionptone: 'Bir doktorun oğlunun babası doktor değildi.',
          questionpttwo: 'Ozaman doktor kim oluyor?',
          answer: 'annesi',
          hint: 'Bu oğulsa ve doktor baba değilse, sadece bir ebeveyn olabilir.',
          isSolved: false,
          rIndex: 31,
        },
        {
          name: 'Demir',
          questionptone: 'Demir çatı, cam duvarlar,yanar ve yanar ve asla düşmez.',
          questionpttwo: '',
          answer: 'Fener',
          hint: 'Cevap bir ışık kaynağıdır',
          isSolved: false,
          rIndex: 32,
        },
        {
          name: 'Kumar',
          questionptone: 'Neleri Katlayabilirsiniz Ama Kırıştıramazsınız?',
          questionpttwo: '',
          answer: 'poker eli',
          hint: 'Kumarı düşün',
          isSolved: false,
          rIndex: 33,
        },
        {
          name: '?',
          questionptone: 'Verilen ama veren tarafından tutulan şey',
          questionpttwo: '',
          answer: 'doğum',
          hint: 'Bu sadece kadınların yapabileceği bir şey',
          isSolved: false,
          rIndex: 34,
        },
        {
          name: 'Su',
          questionptone: 'Saçsız ım ama kafam var. Dişsiz im ama ağızım var.',
          questionpttwo: 'Ben neyim?',
          answer: 'şişe',
          hint: 'su doldurabilirsin',
          isSolved: false,
          rIndex: 35,
        },
        {
          name: 'Eeeewww',
          questionptone: 'Bu küçük yaratık en büyüğünü bile öldürür.',
          questionpttwo: '',
          answer: 'bakteri',
          hint: 'Seni hasta ederim',
          isSolved: false,
          rIndex: 36,
        },
        {
          name: 'kreatif',
          questionptone: 'Fikirlerin büyüdükçe ben küçülüyorum.',
          questionpttwo: 'Ben neyim ?',
          answer: 'kalem',
          hint: 'Benimle yazabilirsin.',
          isSolved: false,
          rIndex: 37,
        },
        {
          name: 'Güven',
          questionptone: 'Birine verdikten sonra ne saklayabilirsiniz?',
          questionpttwo: '',
          answer: 'sır',
          hint: 'Senin icin önemli bir şey',
          isSolved: false,
          rIndex: 38,
        },
        {
          name: 'Sesler',
          questionptone: 'Ağızsız konuşur, kulaksız işitirim.',
          questionpttwo: 'Ben neyim ?',
          answer: 'yankı',
          hint: 'Bir Tünel de bağırdığında olan bir şey.',
          isSolved: false,
          rIndex: 39,
        },
        {
          name: 'Balık',
          questionptone: 'Önce beni yersin, sonra yenilirsin.',
          questionpttwo: 'Ben neyim ?',
          answer: 'olta',
          hint: 'Balıkları çekmek için beni kullanıyorsun',
          isSolved: false,
          rIndex: 40,
        },
        {
          name: 'Rahat',
          questionptone: 'Oturursan sahip olursun, ayakta durursan yok olur',
          questionpttwo: '',
          answer: 'kucak',
          hint: 'Üzerine çoğunlukla bebekler veya çocuklar oturur.',
          isSolved: false,
          rIndex: 41,
        },
        {
          name: 'Meyve',
          questionptone: 'Hangi meyve tarihte çok faydalıdır?',
          questionpttwo: '',
          answer: 'hurma',
          hint: 'Arabistan bununla meşhurdur.',
          isSolved: false,
          rIndex: 42,
        },
        {
          name: 'USA',
          questionptone: 'Her iki uçta yuvarlak ve ortada hi olan nedir?',
          questionpttwo: '',
          answer: 'ohio',
          hint: 'O bir US-Eyaleti',
          isSolved: false,
          rIndex: 43,
        },
        {
          name: 'Hızlı',
          questionptone: 'Güneşin önünden geçiyorum ama gölge yapmıyorum.',
          questionpttwo: 'Ben neyim?',
          answer: 'rüzgar',
          hint: 'Bazen üşütüyorum ama bazen ferahlatiyorum',
          isSolved: false,
          rIndex: 44,
        },
        {
          name: 'Uçmak',
          questionptone: 'Kim gün boyu pencerede oturur, yemek için masaya gider ve geceleri kim saklanır?',
          questionpttwo: '',
          answer: 'sinek',
          hint: 'Sinir bozucu',
          isSolved: false,
          rIndex: 45,
        },
      ],
    },
    {
      level: 'Zor',
      name: 'Son adim',
      riddles: [
        {
          name: 'Harf Dizini',
          questionptone: 'Aşağıdaki dizideki bir sonraki harf nedir:',
          questionpttwo: 'y z v w s t p q?',
          answer: 'm',
          hint: 'Harf çiftlerine dikkat edin ve şemayı arayın',
          isSolved: false,
          rIndex: 46,
        },
        {
          name: 'Odun',
          questionptone: 'Ağaçtan yapılmış ama testereyle kesilemeyen şey',
          questionpttwo: '',
          answer: 'talaş',
          hint: 'Çok küçük Odun',
          isSolved: false,
          rIndex: 47,
        },
        {
          name: 'Matematik',
          questionptone: 'on bir artı iki bir ediyorsa, dokuz artı beş neye eşittir?',
          questionpttwo: '',
          answer: '2',
          hint: 'Saati düşün.',
          isSolved: false,
          rIndex: 48,
        },
        {
          name: 'Küçük',
          questionptone: 'Hangi hayvanın başında ayakları vardır?',
          questionpttwo: '',
          answer: 'bitler',
          hint: 'Küçük bir şey',
          isSolved: false,
          rIndex: 49,
        },
        {
          name: 'Yak',
          questionptone: 'Yaşamıyorum ama büyüyorum; Ciğerlerim yok ama havaya ihtiyacım var; Ağzım yok ama su beni öldürür.',
          questionpttwo: 'Ben neyim?',
          answer: 'ateş',
          hint: 'Ben çoğunlukla kırmızı ve sarıyım',
          isSolved: false,
          rIndex: 50,
        },
        {
          name: 'Yüksek',
          questionptone: 'Ben hayatta değilim ama ölebilirim; Kanatlarım yok ama uçabilirim; Gözlerim yok ama ağlayabilirim.',
          questionpttwo: 'Ben neyim?',
          answer: 'bulut',
          hint: 'Ben gökyüzündeyim',
          isSolved: false,
          rIndex: 51,
        },
        {
          name: 'Hayat',
          questionptone: 'Tüy kadar hafifim ama en güçlü kişi beni bir dakikadan fazla tutamaz.',
          questionpttwo: 'Ben neyim?',
          answer: 'nefes',
          hint: 'Herkesin buna ihtiyacı var',
          isSolved: false,
          rIndex: 52,
        },
        {
          name: 'Akıllı',
          questionptone: 'Madenden alındım ve tahta bir kutuya kapatıldım, oradan asla serbest bırakılmadım ve yine de hemen hemen herkes tarafından kullanıldım.',
          questionpttwo: 'Ben neyim?',
          answer: 'kurşun',
          hint: 'Benimle kurşun kalem üretebilirsin',
          isSolved: false,
          rIndex: 53,
        },
        {
          name: 'Kör',
          questionptone:
            'Dizgin veya eyer olmadan, bir şeyin üzerinden ata biner gibi binerim. Ve benim sayemde bindiklerim, neredeyse kör olmalarına rağmen, görmeleri için yaratıldılar.',
          questionpttwo: 'Ben neyim?',
          answer: 'gözlük',
          hint: 'Görme gücü zayıf olan insanların buna ihtiyacı vardır',
          isSolved: false,
          rIndex: 54,
        },
        {
          name: 'Güven2',
          questionptone: 'Eğer bana sahipsen, beni paylaşmak istersin. Eğer beni paylaşırsan, bana sahip olmazsin.',
          questionpttwo: 'Ben neyim?',
          answer: 'sır',
          hint: 'Güvenilir misin?',
          isSolved: false,
          rIndex: 55,
        },
        {
          name: 'Sayilar',
          questionptone: 'Bu kombinasyondaki sonraki üç harf nedir?',
          questionpttwo: 'B I Ü D B A Y',
          answer: 'sdo',
          hint: 'Saymaya başla',
          isSolved: false,
          rIndex: 56,
        },
        {
          name: 'Dünya',
          questionptone: 'Şehirlerim var ama evlerim yok. Dağlarım var ama ağaçlarım yok. Kıyılarım var ama kum yok.',
          questionpttwo: 'Ben neyim?',
          answer: 'harita',
          hint: 'Benimle yolu bulabilirsin',
          isSolved: false,
          rIndex: 57,
        },
        {
          name: 'Posta',
          questionptone: 'Ne bir köşeye sıkışıp dünyayı dolaşabilir?',
          questionpttwo: '',
          answer: 'pul',
          hint: 'Beni bir mektuba yapıştırabilirsin',
          isSolved: false,
          rIndex: 58,
        },
        {
          name: 'Kar',
          questionptone: 'Dört parmağı ve başparmağı olan ama canlı olmayan nedir?',
          questionpttwo: '',
          answer: 'eldiven',
          hint: 'Çoğu insan beni karda giyer',
          isSolved: false,
          rIndex: 59,
        },
        {
          name: 'SESSİZ',
          questionptone: 'Adını söylediğiniz anda kaybolan nedir?',
          questionpttwo: '',
          answer: 'sessizlik',
          hint: 'Sessiz ol',
          isSolved: false,
          rIndex: 60,
        },
      ],
    },
  ],
};

/*
{
  name: '',
  questionptone: '',
  questionpttwo: '',
  answer: '',
  hint: '',
  isSolved: false,
  rIndex: ,
},
{
  name: '',
  questionptone: '',
  questionpttwo: '',
  answer: '',
  hint: '',
  isSolved: false,
  rIndex: ,
},
{
  name: '',
  questionptone: '',
  questionpttwo: '',
  answer: '',
  hint: '',
  isSolved: false,
  rIndex: ,
},
*/
