import { LevelsStyleProps } from '../../interfaces/screens/levels.interface';

const styleFn = (): LevelsStyleProps => ({
  root: {
    width: '100%',
    height: '100%',
    backgroundColor: '#2F2F2F',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  frame: {
    width: '90%',
    height: '95%',
    overflow: 'hidden',
    borderRadius: 8,
    padding: 3,
  },
  subFrame: {
    width: '100%',
    height: '100%',
    backgroundColor: '#2F2F2F',
    overflow: 'hidden',
    borderRadius: 6,
    padding: 20,
    position: 'relative',
    zIndex: 1,
  },
  riddleInfo: {
    position: 'absolute',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    top: 0,
  },
  riddleInfoText: {
    color: 'white',
    fontSize: 20,
    fontFamily: 'Dosis-SemiBold',
    fontWeight: '500',
  },
  questionContainer: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Dosis-SemiBold',
    fontWeight: '600',
    marginBottom: 60,
  },
  question: {
    color: 'white',
    fontSize: 20,
    fontFamily: 'Dosis-SemiBold',
    fontWeight: '600',
  },
  answerInput: {
    color: 'white',
    fontSize: 20,
    fontFamily: 'Dosis-SemiBold',
    backgroundColor: '#2F2F2F',
    fontWeight: '600',
    width: '100%',
    borderRadius: 8,
    paddingHorizontal: 20,
    textAlign: 'center',
  },
  button: {
    width: 55,
    height: 55,
    borderRadius: 8,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 3,
    margin: 2.5,
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontFamily: 'Dosis-SemiBold',
    fontWeight: 'bold',
    textAlign: 'center',
    borderRadius: 7,
    width: '100%',
    height: '100%',
    textAlignVertical: 'center',
    backgroundColor: '#2F2F2F',
    position: 'absolute',
  },
  linear: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: -1,
  },
  inputContainer: {
    width: '100%',
    borderRadius: 8,
    overflow: 'hidden',
    padding: 3,
  },
  inputSubContainer: {
    zIndex: 1,
    borderRadius: 6,
  },
  levels: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Dosis-SemiBold',
    marginVertical: 3,
    marginTop: 10,
  },
  levelRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  chapter: {
    marginBottom: 30,
    top: 30,
  },
  headerlabel: {
    color: 'white',
    fontSize: 20,
    fontFamily: 'Dosis-SemiBold',
    marginBottom: 20,
  },
  tick: {
    width: 28,
    height: 28,
    zIndex: 10,
  },
  tickText: {
    color: '#2F2F2F',
    fontSize: 16,
    fontFamily: 'Dosis-SemiBold',
    fontWeight: 'bold',
    textAlign: 'center',
    borderRadius: 7,
    width: '100%',
    height: '100%',
    textAlignVertical: 'center',
    backgroundColor: '#2F2F2F',
    position: 'absolute',
  },
  tickBox: {
    width: 55,
    height: 55,
    borderRadius: 8,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 3,
    margin: 2.5,
  },
  lockedText: {
    fontFamily: 'Dosis-SemiBold',
    fontSize: 13,
    fontWeight: 'bold',
    textAlign: 'center',
    justifyContent: 'center',
    display: 'flex',
    zIndex: 10,
    color: 'white',
    bottom: 12,
  },
  lock: {
    width: 32,
    height: 32,
    zIndex: 10,
    top: 8,
  },
});

export default styleFn;
